const types = {
    SET_BASEURL: 'SET_BASEURL',
    UPDATE_FIELDS: 'UPDATE_FIELDS',
    TOGGLESELECT_FIELD: 'TOGGLESELECT_FIELD',
    TOGGLE_FACETS_WINDOW: 'TOGGLE_FACETS_WINDOW',

    //Only for a single field
    REQUEST_FACETS: 'REQUEST_FACETS',
    UPDATE_STATS: 'UPDATE_STATS',
    UPDATE_FACETS: 'UPDATE_FACETS',
    CHANGE_FACETS_OPTIONS: 'CHANGE_FACETS_OPTIONS',


    //Add filters
    ADD_FILTER: 'ADD_FILTER',
    REMOVE_FILTER: 'REMOVE_FILTER',
    FINISH_FILTER_EDITING: 'FINISH_FILTER_EDITING',
    START_FILTER_EDITING: 'START_FILTER_EDITING',
    ADD_TO_EDITING_FILTER: 'ADD_TO_EDITING_FILTER',

    SET_SORT:'SET_SORT',

    // 'FAIL_TO_FETCH'
    UPDATE_DATA: 'UPDATE_DATA',
    UPDATE_PAGINATION: 'UPDATE_PAGINATION',

    //Time Slider -- on
    SET_TIMESLIDER_OPTIONS:'SET_TIMESLIDER_OPTIONS',

    //API calls tracking
    ADD_FETCHING_URL:'ADD_FETCHING_URL',
    REMOVE_FETCHING_URL:'REMOVE_FETCHING_URL',
    ADD_FETCHING_ERROR:'ADD_FETCHING_ERROR',
    REMOVE_FETCHING_ERROR:'REMOVE_FETCHING_ERROR'

}

export default types;
