const types = {
	SET_BASEURL:'SET_BASEURL',
	REQUEST_FIELDS:'REQUEST_FIELDS',
	UPDATE_FIELDS:'UPDATE_FIELDS',
	TOGGLESELECT_FIELD:'TOGGLESELECT_FIELD',

	//Only for a single field
	REQUEST_FACETS:'REQUEST_FACETS',
	UPDATE_FACETS:'UPDATE_FACETS'
	// 'FAIL_TO_FETCH'
}

export default types;
