const types = {
	SET_BASEURL:'SET_BASEURL',
	REQUEST_FIELDS:'REQUEST_FIELDS',
	UPDATE_FIELDS:'UPDATE_FIELDS',
	TOGGLESELECT_FIELD:'TOGGLESELECT_FIELD',

	//Only for a single field
	REQUEST_FACETS:'REQUEST_FACETS',
	UPDATE_FACETS:'UPDATE_FACETS',
	CHANGE_SEARCHTEXT_FACETS:'CHANGE_SEARCHTEXT_FACETS',


	//Add filters
	ADD_FILTER:'ADD_FILTER',
	REMOVE_FILTER:'REMOVE_FILTER',

	// 'FAIL_TO_FETCH'
	UPDATE_DATA:'UPDATE_DATA',
	UPDATE_PAGINATION:'UPDATE_PAGINATION',
}

export default types;
